export const IMAGES = {
    
    user : require('../assets/images/user.png'),
    card : require('../assets/images/card.png'),
    card1 : require('../assets/images/card1.png'),
    google2 : require('../assets/images/icons/google2.png'),
    facebook : require('../assets/images/icons/facebook.png'),
    Home: require('../assets/images/icons/home.png'),
    heart: require('../assets/images/icons/heart.png'),
    mycart: require('../assets/images/icons/shopping2.png'),
    Category: require('../assets/images/icons/document.png'),
    user2: require('../assets/images/icons/user.png'),
    user3: require('../assets/images/icons/user4.png'),
    grid3: require('../assets/images/icons/grid3.png'),
    grid4: require('../assets/images/icons/grid4.png'),
    shose: require('../assets/images/icons/shose.png'),
    ball: require('../assets/images/icons/bell.png'),
    close: require('../assets/images/icons/close.png'),
    check: require('../assets/images/icons/check.png'),
    delete: require('../assets/images/icons/delete.png'),
    Chat: require('../assets/images/icons/Chat.png'),
    Star: require('../assets/images/icons/Star.png'),
    wallet: require('../assets/images/icons/wallet.png'),
    Location: require('../assets/images/icons/Location.png'),
    Filter: require('../assets/images/icons/Filter.png'),
    Notification: require('../assets/images/icons/Notification.png'),
    search: require('../assets/images/icons/search.png'),
    list: require('../assets/images/icons/list.png'),
    grid: require('../assets/images/icons/grid.png'),
    arrowup: require('../assets/images/icons/arrowup.png'),
    filter2: require('../assets/images/icons/filter2.png'),
    shop: require('../assets/images/icons/shop.png'),
    Bag: require('../assets/images/icons/Bag.png'),
    plus: require('../assets/images/icons/plus.png'),
    dollar: require('../assets/images/icons/dollar.png'),
    payment: require('../assets/images/icons/payment.png'),
    folder: require('../assets/images/icons/folder.png'),
    bank: require('../assets/images/icons/bank.png'),
    shieldcheck: require('../assets/images/icons/shieldcheck.png'),
    card2: require('../assets/images/icons/card2.png'),
    write: require('../assets/images/icons/write.png'),
    downaeeowsmall: require('../assets/images/icons/downaeeowsmall.png'),
    home: require('../assets/images/icons/home4.png'),
    producta: require('../assets/images/icons/producta.png'),
    components: require('../assets/images/icons/components.png'),
    star: require('../assets/images/icons/star2.png'), 
    heart2: require('../assets/images/icons/heart2.png'), 
    order: require('../assets/images/icons/order.png'), 
    shopping: require('../assets/images/icons/shopping3.png'), 
    chat: require('../assets/images/icons/chat2.png'), 
    logout: require('../assets/images/icons/logout.png'), 
    call: require('../assets/images/icons/call.png'), 
    happy: require('../assets/images/icons/happy.png'), 
    send: require('../assets/images/icons/send.png'), 
    volume: require('../assets/images/icons/volume.png'), 
    phone: require('../assets/images/icons/phone.png'), 
    audio: require('../assets/images/icons/audio.png'), 
    audiomute: require('../assets/images/icons/audiomute.png'), 
    sun: require('../assets/images/icons/sun.png'), 
    darkMode: require('../assets/images/icons/moon.png'), 


    onborder1 : require('../assets/images/onbording/pic1.png'),
    item1: require('../assets/images/item/pic1.png'),
    item2: require('../assets/images/item/pic2.png'),
    item3: require('../assets/images/item/pic3.png'),
    item4: require('../assets/images/item/pic4.png'),
    item5: require('../assets/images/item/pic5.png'),
    item6: require('../assets/images/item/pic6.png'),
    item7: require('../assets/images/item/pic7.png'),
    item8: require('../assets/images/item/pic8.png'),


    item9: require('../assets/images/item2/pic1.png'),
    item10: require('../assets/images/item2/pic2.png'),
    item11: require('../assets/images/item2/pic3.png'),
    item12: require('../assets/images/item2/pic4.png'),
    item13: require('../assets/images/item2/pic5.png'),
    item14: require('../assets/images/item2/pic6.png'),
    item15: require('../assets/images/item2/pic7.png'),
    item16: require('../assets/images/item2/pic8.png'),
    item17: require('../assets/images/item2/pic9.png'),

    item18: require('../assets/images/item/pic9.png'),
    item19: require('../assets/images/item/pic10.png'),


    brand1: require('../assets/images/brand/pic1.png'),
    brand2: require('../assets/images/brand/pic2.png'),
    brand3: require('../assets/images/brand/pic3.png'),
    brand4: require('../assets/images/brand/pic4.png'),
    brand5: require('../assets/images/brand/pic5.png'),


    small1: require('../assets/images/small/pic5.png'),
    small2: require('../assets/images/small/pic6.png'),
    small3: require('../assets/images/small/pic7.png'),
    small4: require('../assets/images/small/pic8.png'),
    small5: require('../assets/images/small/pic9.png'),
    small6: require('../assets/images/small/pic10.png'),
    small7: require('../assets/images/small/pic11.png'),

    product1: require('../assets/images/product/pic1.png'),
    product2: require('../assets/images/product/pic2.png'),
    product3: require('../assets/images/product/pic3.png'),
    product4: require('../assets/images/product/pic4.png'),

    ads1: require('../assets/images/ads/pic1.png'),
    ads2: require('../assets/images/ads/pic2.png'),
    ads3: require('../assets/images/ads/pic3.png'),

}